# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "2.7"
  - "2.6"
  - "pypy"

install: pip install -r requirements.txt && pip install -r requirements-test.txt

script: make test
